// <auto-generated />
using System;
using EcommerceWebsite.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EcommerceWebsite.Data.Migrations
{
    [DbContext(typeof(EcomWebDbContext))]
    [Migration("20211010145713_capnhatGianGiao")]
    partial class capnhatGianGiao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.BoPhan", b =>
                {
                    b.Property<string>("MaBP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenBP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBP");

                    b.ToTable("BOPHAN");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.CTHoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("money");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("money");

                    b.HasKey("MaHD", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("CTHOADON");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.CTNhapSP", b =>
                {
                    b.Property<string>("MaNhap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("money");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("money");

                    b.HasKey("MaNhap", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("CTNHAPSP");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.DanhGiaSP", b =>
                {
                    b.Property<string>("MaDG")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnhDG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDG");

                    b.HasIndex("MaSP")
                        .IsUnique()
                        .HasFilter("[MaSP] IS NOT NULL");

                    b.ToTable("DANHGIASP");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.DiaChiKH", b =>
                {
                    b.Property<string>("MaDiaChiKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChiGH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("MaDiaChiKH", "MaKH");

                    b.HasIndex("MaKH");

                    b.ToTable("DIACHIKH");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.DinhLuong", b =>
                {
                    b.Property<string>("MaTT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GiaTri")
                        .HasColumnType("real");

                    b.HasKey("MaTT", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("DINHLUONG");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.GiaoHang", b =>
                {
                    b.Property<string>("MaGH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayDuKienGiao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiHienTai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGH");

                    b.HasIndex("MaHD")
                        .IsUnique()
                        .HasFilter("[MaHD] IS NOT NULL");

                    b.ToTable("GIAOHANG");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.HangSanPham", b =>
                {
                    b.Property<string>("MaHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHang");

                    b.ToTable("HANGSANPHAM");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaDiaChiKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiGH")
                        .HasColumnType("money");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("money");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("money");

                    b.Property<string>("TrangThaiTT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKM");

                    b.HasIndex("MaDiaChiKH", "MaKH");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKH");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKT")
                        .HasColumnType("datetime2");

                    b.Property<float>("PhanTram")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKM");

                    b.ToTable("KHUYENMAI");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.LichSuGia", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayBD")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gia")
                        .HasColumnType("money");

                    b.HasKey("MaSP", "NgayBD");

                    b.ToTable("LICHSUGIA");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.LoaiSanPham", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaLoai");

                    b.ToTable("LOAISANPHAM");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.MauSanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenMau")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSP", "TenMau");

                    b.ToTable("MAUSANPHAM");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenNCC")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaNCC");

                    b.ToTable("NHACUNGCAP");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaBP");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhanXetSP", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soSao")
                        .HasColumnType("int");

                    b.HasKey("MaKH", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("NHANXETSP");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhapSanPham", b =>
                {
                    b.Property<string>("MaNhap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNCC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("money");

                    b.HasKey("MaNhap");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("NHAPSANPHAM");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHang")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLoaiSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("0");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaSP");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaLoaiSP");

                    b.ToTable("SANPHAM");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.ThuocTinh", b =>
                {
                    b.Property<string>("MaTT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTT");

                    b.ToTable("THUOCTINH");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.TinhTrangGH", b =>
                {
                    b.Property<string>("MaGH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTTGH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGH", "MaTTGH");

                    b.ToTable("TINHTRANGIAOHANG");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.CTHoaDon", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.HoaDon", "hoaDon")
                        .WithMany("cTHoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceWebsite.Data.Entities.SanPham", "sanPham")
                        .WithMany("cTHoaDons")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoaDon");

                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.CTNhapSP", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.NhapSanPham", "nhapSanPham")
                        .WithMany("cTNhapSPs")
                        .HasForeignKey("MaNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceWebsite.Data.Entities.SanPham", "sanPham")
                        .WithMany("cTNhapSPs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nhapSanPham");

                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.DanhGiaSP", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.SanPham", "sanPhams")
                        .WithOne("danhGiaSP")
                        .HasForeignKey("EcommerceWebsite.Data.Entities.DanhGiaSP", "MaSP");

                    b.Navigation("sanPhams");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.DiaChiKH", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.KhachHang", "khachHang")
                        .WithMany("diaChiKHs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHang");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.DinhLuong", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.SanPham", "sanPham")
                        .WithMany("dinhLuongs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceWebsite.Data.Entities.ThuocTinh", "thuocTinh")
                        .WithMany("dinhLuongs")
                        .HasForeignKey("MaTT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sanPham");

                    b.Navigation("thuocTinh");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.GiaoHang", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.HoaDon", "hoaDon")
                        .WithOne("giaoHang")
                        .HasForeignKey("EcommerceWebsite.Data.Entities.GiaoHang", "MaHD");

                    b.Navigation("hoaDon");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.HoaDon", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.KhachHang", "khachHang")
                        .WithMany("hoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceWebsite.Data.Entities.KhuyenMai", "khuyenMai")
                        .WithMany("hoaDons")
                        .HasForeignKey("MaKM");

                    b.HasOne("EcommerceWebsite.Data.Entities.DiaChiKH", "diaChiKH")
                        .WithMany("hoaDons")
                        .HasForeignKey("MaDiaChiKH", "MaKH");

                    b.Navigation("diaChiKH");

                    b.Navigation("khachHang");

                    b.Navigation("khuyenMai");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.LichSuGia", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.SanPham", "sanPham")
                        .WithMany("lishSuGias")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.MauSanPham", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.SanPham", "sanPham")
                        .WithMany("mauSanPhams")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhanVien", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.BoPhan", "BoPhan")
                        .WithMany("nhanViens")
                        .HasForeignKey("MaBP");

                    b.Navigation("BoPhan");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhanXetSP", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.KhachHang", "KhachHang")
                        .WithMany("nhanXetSPs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceWebsite.Data.Entities.SanPham", "sanPham")
                        .WithMany("nhanXetSPs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("sanPham");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhapSanPham", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.NhaCungCap", "nhaCungCap")
                        .WithMany("nhapSanPhams")
                        .HasForeignKey("MaNCC");

                    b.HasOne("EcommerceWebsite.Data.Entities.NhanVien", "nhanVien")
                        .WithMany("nhapSanPhams")
                        .HasForeignKey("MaNV");

                    b.Navigation("nhaCungCap");

                    b.Navigation("nhanVien");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.SanPham", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.HangSanPham", "hangSanPhams")
                        .WithMany("sanPhams")
                        .HasForeignKey("MaHang");

                    b.HasOne("EcommerceWebsite.Data.Entities.LoaiSanPham", "loaiSanPhams")
                        .WithMany("sanPhams")
                        .HasForeignKey("MaLoaiSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hangSanPhams");

                    b.Navigation("loaiSanPhams");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.TinhTrangGH", b =>
                {
                    b.HasOne("EcommerceWebsite.Data.Entities.GiaoHang", "giaoHang")
                        .WithMany("tinhTrangGHs")
                        .HasForeignKey("MaGH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("giaoHang");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.BoPhan", b =>
                {
                    b.Navigation("nhanViens");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.DiaChiKH", b =>
                {
                    b.Navigation("hoaDons");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.GiaoHang", b =>
                {
                    b.Navigation("tinhTrangGHs");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.HangSanPham", b =>
                {
                    b.Navigation("sanPhams");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.HoaDon", b =>
                {
                    b.Navigation("cTHoaDons");

                    b.Navigation("giaoHang");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.KhachHang", b =>
                {
                    b.Navigation("diaChiKHs");

                    b.Navigation("hoaDons");

                    b.Navigation("nhanXetSPs");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.KhuyenMai", b =>
                {
                    b.Navigation("hoaDons");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.LoaiSanPham", b =>
                {
                    b.Navigation("sanPhams");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhaCungCap", b =>
                {
                    b.Navigation("nhapSanPhams");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhanVien", b =>
                {
                    b.Navigation("nhapSanPhams");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.NhapSanPham", b =>
                {
                    b.Navigation("cTNhapSPs");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.SanPham", b =>
                {
                    b.Navigation("cTHoaDons");

                    b.Navigation("cTNhapSPs");

                    b.Navigation("danhGiaSP");

                    b.Navigation("dinhLuongs");

                    b.Navigation("lishSuGias");

                    b.Navigation("mauSanPhams");

                    b.Navigation("nhanXetSPs");
                });

            modelBuilder.Entity("EcommerceWebsite.Data.Entities.ThuocTinh", b =>
                {
                    b.Navigation("dinhLuongs");
                });
#pragma warning restore 612, 618
        }
    }
}
